"""Extra terminal freedoms must remain an exact planar circular hook."""
import copy
import unittest
import numpy as np
from algorithms.rebar_control_curves import _fit_piece, _terminal_model, _project
from test_rebar_control_curves import terminal_fixture, tube

class ParametricTerminalTests(unittest.TestCase):
    def test_missing_arc_keeps_inference_but_claims_locally_verified_surfaces(self):
        from scipy.spatial import cKDTree
        from algorithms.rebar_control_curves import fit_curved_pieces
        from algorithms.rebar_design_curves import build_design_curve_pieces
        from test_rebar_control_terminal_completion import terminal_inventory
        inventory,rows=terminal_inventory();piece=build_design_curve_pieces(inventory)[0]
        piece['_designAnchors']=[np.array([0.,0.,0.])]
        piece['_designTangents']=[np.array([1.,0.,0.])]
        curve,_=_terminal_model(piece,{'body':rows[0]})[0](np.array([.003,.001,0.,0.,.021,2.38]))
        segments=[(a,b) for i,(a,b) in enumerate(zip(curve[:-1],curve[1:])) if not 26<=i<45]
        # Each disconnected patch has its own exact local radial frame.
        patches=[tube(a+(b-a)*np.linspace(0,1,8,endpoint=False)[:,None]) for a,b in segments]
        points=np.vstack([p for p,n in patches]);normals=np.vstack([n for p,n in patches])
        owner=np.zeros(len(points),np.uint32);status=np.full(len(points),2,np.uint8)
        reports,_=fit_curved_pieces(points,normals,inventory,rows,status,owner,
            tree=cKDTree(points),source_ids=np.arange(len(points)))
        self.assertEqual(reports[0]['inferenceMethod'],'scan-guided-parametric-terminal')
        self.assertEqual(reports[0]['status'],'pending')
        self.assertEqual(reports[0]['pointCount'],0)
        self.assertGreater(reports[0].get('localSupport', {}).get('pointCount', 0), 24)
        self.assertEqual(np.count_nonzero(owner), reports[0]['localSupport']['pointCount'])
        np.testing.assert_array_equal(owner > 0, status == 1)

    def test_parameter_changes_preserve_circle_plane_tangency_and_body_anchor(self):
        piece,rows=terminal_fixture();before=copy.deepcopy(rows)
        model,seed,lower,upper,*_=_terminal_model(piece,rows,articulated=True)
        fixed=model(seed)[0][0].copy();rng=np.random.default_rng(18)
        for _ in range(16):
            p=lower+(upper-lower)*rng.uniform(.15,.85,len(seed))
            curve,meta=model(np.r_[p,.012])
            center=np.array(meta['arcCenterM']);normal=meta['normal'];t=meta['arcTangent']
            np.testing.assert_allclose(np.linalg.norm(curve[16:57]-center,axis=1),p[4],atol=1e-10)
            np.testing.assert_allclose((curve[16:57]-center)@normal,0.,atol=1e-10)
            expected=np.cos(p[5])*t+np.sin(p[5])*np.cross(normal,t)
            np.testing.assert_allclose(curve[-1]-curve[-2],.012*expected,atol=1e-10)
            np.testing.assert_array_equal(curve[0],fixed)
        self.assertEqual(rows,before)

    def test_tail_extent_is_one_continuous_parameter_and_rejects_plane_or_search_cutoff(self):
        from algorithms.rebar_control_curves import _observed_terminal_extent
        curve=np.array([[-.02,0.,0.],[0.,0.,0.],[.04,0.,0.]])
        for length in [.016,.06]:
            centers=np.c_[np.linspace(.001,length,100),np.zeros((100,2))]
            p,n=tube(centers)
            value=_observed_terminal_extent(p,n,curve,.003)
            self.assertIsNotNone(value)
            self.assertLess(abs(value-length),.001)
            # Disconnected points further along cannot lengthen this tail.
            far,fn=tube(centers+np.array([length+.02,0.,0.]))
            value=_observed_terminal_extent(np.vstack((p,far)),np.vstack((n,fn)),curve,.003)
            self.assertLess(abs(value-length),.001)
        centers=np.c_[np.linspace(.001,.12,400),np.zeros((400,2))]
        p,n=tube(centers)
        self.assertIsNone(_observed_terminal_extent(p,n,curve,.003))
        p,n=tube(centers[:100],angles=np.array([0.]))
        self.assertIsNone(_observed_terminal_extent(p,n,curve,.003))

    def test_lifted_hook_is_fitted_without_deforming_the_circle(self):
        piece,rows=terminal_fixture();before=copy.deepcopy(rows)
        # Independent circular arc with a pitched incoming tangent and rotated plane.
        pitch,roll=.28,.42
        tangent=np.array([np.cos(pitch),0.,np.sin(pitch)])
        across=np.array([-np.sin(pitch),0.,np.cos(pitch)])
        bend=np.cos(roll)*np.array([0.,1.,0.])+np.sin(roll)*across
        start=np.array([.006,.008,.003]);phi=np.linspace(0,2.85,41);radius=.023
        arc=start+radius*np.sin(phi)[:,None]*tangent+radius*(1-np.cos(phi))[:,None]*bend
        tip=arc[-1]+.04*(np.cos(phi[-1])*tangent+np.sin(phi[-1])*bend)
        # Fixed body transition is generated by its endpoint/tangents, not free nodes.
        from algorithms.rebar_control_curves import _bezier
        lead=_bezier(np.array([-.08,0.,0.]),start,np.array([1.,0.,0.]),tangent)
        truth=np.vstack((lead[:-1],arc,tip))
        dense=np.vstack([a+(b-a)*np.linspace(0,1,8,endpoint=False)[:,None] for a,b in zip(truth[:-1],truth[1:])])
        directions=np.gradient(dense,axis=0);directions/=np.linalg.norm(directions,axis=1)[:,None]
        sides=np.cross(np.array([0.,0.,1.]),directions);sides/=np.linalg.norm(sides,axis=1)[:,None]
        ups=np.cross(directions,sides);angles=np.linspace(-1.2,1.2,24)
        normals=(np.cos(angles)[None,:,None]*sides[:,None,:]+np.sin(angles)[None,:,None]*ups[:,None,:]).reshape(-1,3)
        points=np.repeat(dense,24,axis=0)+.003*normals
        result,reason=_fit_piece(points,normals,piece,rows,articulated=True)
        self.assertIsNotNone(result,reason)
        self.assertLess(np.quantile(_project(truth,result['curve'])[0],.95),.0015)
        self.assertEqual(rows,before)
        center=np.array(result['meta']['arcCenterM']);normal=np.array(result['meta']['normal'])
        fitted_arc=result['curve'][16:57]
        np.testing.assert_allclose(np.linalg.norm(fitted_arc-center,axis=1),result['meta']['bendRadiusM'],atol=1e-10)
        np.testing.assert_allclose((fitted_arc-center)@normal,0.,atol=1e-10)

if __name__=='__main__':unittest.main()
